/* ============================================================================
   Veridian Studio — Ingest / New Source.
   Sources -> Layers model: a source produces annotation layers (prediction or
   ground-truth). This file owns the Source hub + the video auto-label flow +
   the shared, reusable pipeline (ProcessingView) and DoneView. The import-
   labeled flow lives in ingest-import.jsx and reuses the shared pieces.
   Exposes: IngestScreen + (window) ProcessingView, DoneView, DropZone,
   ingest helpers.
   ========================================================================== */

const SOURCE_FPS = 30;
const SAMPLE_MODES = [
  { id: "1fps", label: "1 fps", div: 30 },
  { id: "2fps", label: "2 fps", div: 15 },
  { id: "5fps", label: "5 fps", div: 6 },
  { id: "scene", label: "scene-change", div: 42 },
  { id: "all", label: "every frame", div: 1 },
];

const USE_CASES = [
  { id: "street", label: "Automotive / Street", models: ["amod"], dataset: "street_scenes", palette: "dusk", icon: "car" },
  { id: "faces", label: "Access Control / Faces", models: ["fd", "fr"], dataset: "access_faces", palette: "indoor", icon: "face" },
  { id: "qr", label: "Warehouse / QR", models: ["qrcode"], dataset: "warehouse_qr", palette: "warehouse", icon: "qr" },
  { id: "distance", label: "Distance / Range Eval", models: ["amod", "fd", "qrcode"], dataset: "distance_eval", palette: "dusk", icon: "ruler" },
];

const SAMPLE_VIDEOS = [
  { name: "ring_cam_driveway_0412.mp4", dur: 184, w: 1920, h: 1080, size: 248, palette: "dusk", uc: "street" },
  { name: "lobby_entrance_am.mov", dur: 96, w: 1280, h: 720, size: 121, palette: "indoor", uc: "faces" },
  { name: "forklift_aisle22.mp4", dur: 312, w: 2560, h: 1440, size: 512, palette: "warehouse", uc: "qr" },
  { name: "hwy_onramp_dashcam.mp4", dur: 240, w: 1920, h: 1080, size: 380, palette: "dusk", uc: "street" },
  { name: "range_test_5to30ft.mp4", dur: 150, w: 1920, h: 1080, size: 210, palette: "dusk", uc: "distance" },
];

function fmtDur(s) { const m = Math.floor(s / 60); return m + ":" + String(Math.round(s % 60)).padStart(2, "0"); }
function estFrames(dur, modeId) { const m = SAMPLE_MODES.find((x) => x.id === modeId); return Math.max(1, Math.round((dur * SOURCE_FPS) / m.div)); }
function posterFor(palette, seed) {
  const d = window.VD.datasets.find((x) => x.palette === palette && x.kind === "vision") || window.VD.datasets[0];
  return d.images[seed % d.images.length];
}
function resolveDsName(uc) {
  if (!uc) return "";
  if (uc.dataset) return window.VD.getDataset(uc.dataset)?.name || uc.datasetName || uc.label;
  return uc.datasetName || uc.label;
}
function ucColor(uc) { return vhelp.modelColor(uc.models[0] === "fd" ? "fd" : uc.models[0]); }

let _vid = 0;
function makeVideo(spec) {
  return {
    key: "v" + (++_vid), name: spec.name, dur: spec.dur, w: spec.w, h: spec.h, size: spec.size,
    palette: spec.palette || "dusk", uc: spec.uc || null, mode: "2fps", url: spec.url || null,
    poster: posterFor(spec.palette || "dusk", _vid),
  };
}

/* ============================ SOURCE HUB ================================== */
function SourceHub({ onPick }) {
  const cards = [
    { id: "local", icon: "folder", color: "var(--m-amod)", title: "Local dataset folder", layer: "prediction layer", desc: "Pick a folder under the datasets root. Run the sensVeridian oracle models over its images (or split videos into frames) and store predictions you then verify.", produces: "Runs models" },
    { id: "video", icon: "film", color: "var(--m-fd)", title: "Auto-label video", layer: "prediction layer", desc: "Split clips into frames and run sensVeridian oracles to generate candidate labels you then verify.", produces: "Runs models" },
    { id: "import", icon: "upload", color: "var(--m-fr)", title: "Import labeled data", layer: "ground-truth layer", desc: "Bring your own labels — images + COCO/YOLO, CSV/parquet, or audio + segments. No inference; labels become editable ground-truth.", produces: "No models" },
    { id: "connect", icon: "link", color: "var(--m-qr)", title: "Watch a folder", layer: "watched layer", desc: "Watch a local folder; new media auto-ingests on a schedule with your chosen pipeline.", produces: "Streaming" },
  ];
  return (
    <>
      <TopBar crumbs={[{ label: "New source" }]} />
      <div className="scroll" style={{ flex: 1, padding: "30px 26px" }}>
        <div style={{ maxWidth: 880, margin: "0 auto" }}>
          <div style={{ marginBottom: 8, fontSize: 21, fontWeight: 700, letterSpacing: "-0.01em" }}>Add a source</div>
          <div style={{ fontSize: 13.5, color: "var(--tx-1)", marginBottom: 4, maxWidth: 620 }}>
            Every dataset is <b style={{ color: "var(--tx-0)" }}>media + annotation layers</b>. A source produces a layer — generated by a model, or brought as ground-truth. Verification then diffs any two layers.
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginTop: 22 }}>
            {cards.map((c) => (
              <button key={c.id} onClick={() => onPick(c.id)} className="card" style={{ padding: 20, textAlign: "left", display: "flex", flexDirection: "column", gap: 12, transition: "border-color .14s, transform .1s" }}
                onMouseEnter={(e) => { e.currentTarget.style.borderColor = c.color; e.currentTarget.style.transform = "translateY(-2px)"; }}
                onMouseLeave={(e) => { e.currentTarget.style.borderColor = "var(--line)"; e.currentTarget.style.transform = "none"; }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                  <div style={{ width: 44, height: 44, borderRadius: 11, background: "var(--bg-2)", display: "grid", placeItems: "center", color: c.color }}><Icon name={c.icon} size={23} /></div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 15.5, fontWeight: 700 }}>{c.title}</div>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 3 }}>
                      <Icon name="layers" size={12} style={{ color: c.color }} />
                      <span style={{ fontSize: 11, color: c.color, fontWeight: 600 }}>→ {c.layer}</span>
                    </div>
                  </div>
                  <Icon name="arrowR" size={18} style={{ color: "var(--tx-3)" }} />
                </div>
                <div style={{ fontSize: 12.5, color: "var(--tx-1)", lineHeight: 1.5 }}>{c.desc}</div>
                <div style={{ marginTop: "auto", paddingTop: 8 }}>
                  <span className="chip" style={{ borderColor: "var(--line)", color: "var(--tx-2)" }}><span className="dot" style={{ background: c.color }} />{c.produces}</span>
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

/* ============================ VIDEO AUTO-LABEL FLOW ====================== */
function VideoIngestFlow({ onExit }) {
  const ctx = React.useContext(VDCtx);
  const { t, setTweak } = ctx;
  const [stage, setStage] = React.useState("compose");
  const [videos, setVideos] = React.useState(() => SAMPLE_VIDEOS.slice(0, 3).map(makeVideo));
  const [customCases, setCustomCases] = React.useState([]);
  const [addTagFor, setAddTagFor] = React.useState(null);
  const fileRef = React.useRef(null);
  const useCases = React.useMemo(() => [...USE_CASES, ...customCases], [customCases]);

  const addSamples = () => setVideos((v) => { const ex = new Set(v.map((x) => x.name)); const next = SAMPLE_VIDEOS.filter((s) => !ex.has(s.name)).map(makeVideo); return next.length ? [...v, ...next] : v; });
  const onFiles = (e) => {
    const files = [...(e.target.files || [])];
    const added = files.map((f) => {
      const url = URL.createObjectURL(f);
      const v = makeVideo({ name: f.name, dur: 120, w: 1920, h: 1080, size: Math.round(f.size / 1048576), palette: "dusk", url });
      const probe = document.createElement("video"); probe.preload = "metadata"; probe.src = url;
      probe.onloadedmetadata = () => setVideos((vs) => vs.map((x) => x.key === v.key ? { ...x, dur: probe.duration || 120, w: probe.videoWidth || x.w, h: probe.videoHeight || x.h } : x));
      return v;
    });
    setVideos((v) => [...v, ...added]); e.target.value = "";
  };
  const update = (key, patch) => setVideos((v) => v.map((x) => x.key === key ? { ...x, ...patch } : x));
  const remove = (key) => setVideos((v) => v.filter((x) => x.key !== key));
  const setAllMode = (mode) => setVideos((v) => v.map((x) => ({ ...x, mode })));

  const createCustomCase = (data) => {
    let base = data.label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 24) || "tag";
    let id = base, i = 2; while (useCases.some((u) => u.id === id)) id = base + "_" + i++;
    const palette = data.models.includes("amod") ? "dusk" : (data.models.includes("fd") || data.models.includes("fr")) ? "indoor" : data.models.includes("qrcode") ? "warehouse" : "dusk";
    const uc = { id, label: data.label, models: data.models, dataset: null, datasetName: data.label, palette, icon: data.icon, isNew: true };
    setCustomCases((c) => [...c, uc]);
    if (addTagFor && addTagFor !== "__global") update(addTagFor, { uc: id, palette, poster: posterFor(palette, id.length + 3) });
    setAddTagFor(null);
  };

  const finishIngest = () => {
    const updated = customCases.map((uc) => {
      if (uc.isNew && !uc.created) {
        const grp = videos.filter((v) => v.uc === uc.id);
        if (grp.length) {
          const frames = grp.reduce((s, v) => s + estFrames(v.dur, v.mode), 0);
          const n = Math.min(40, Math.max(10, Math.round(frames / 600)));
          const ds = window.VD.createDataset({ name: uc.label, desc: `Ingested via the “${uc.label}” use-case tag.`, models: uc.models, palette: uc.palette, n });
          return { ...uc, dataset: ds.id, created: true };
        }
      }
      return uc;
    });
    setCustomCases(updated); setStage("done");
    // record the ingest job through the backend seam (server does the real
    // frame-split + inference; the mock just acknowledges it)
    try {
      window.VeridianAPI && window.VeridianAPI.createIngestJob({
        source: "video",
        trustThreshold: t.autoAccept ? t.trustThreshold : null,
        groups: groups.map((g) => ({ tag: g.uc.id, label: g.uc.label, models: g.uc.models, videos: g.vs.length, frames: g.frames, dataset: g.uc.dataset, isNew: !!g.uc.isNew })),
      });
    } catch (e) { /* offline */ }
  };

  const tagged = videos.filter((v) => v.uc);
  const untagged = videos.length - tagged.length;
  const totalFrames = tagged.reduce((s, v) => s + estFrames(v.dur, v.mode), 0);
  const groups = useCases.map((uc) => { const vs = videos.filter((v) => v.uc === uc.id); return { uc, vs, frames: vs.reduce((s, v) => s + estFrames(v.dur, v.mode), 0) }; }).filter((g) => g.vs.length);

  if (stage === "processing") {
    const allModels = [...new Set(groups.flatMap((g) => g.uc.models))];
    const log = [
      "» connecting to veridian-db.lattice.internal (PostgreSQL)",
      ...groups.flatMap((g) => g.vs.map((v) => `» queued ${v.name}  →  #${g.uc.id}`)),
      "» ffmpeg decode: " + groups.reduce((s, g) => s + g.vs.length, 0) + " streams",
      "» sampling frames at configured rates",
      "» loading oracle weights: " + allModels.join(", "),
      "» running inference on sampled frames",
      t.autoAccept ? `» auto-accepting detections ≥ ${t.trustThreshold.toFixed(2)} with model consensus` : "» all detections queued for review",
      "» sha-256 content hashing + dedup",
      "» upserting predictions_summary + predictions_raw",
      "✓ ingest complete",
    ];
    return <ProcessingView title="sensVeridian is processing your videos" subtitle="Splitting into frames, auto-labelling, and combining per tag."
      stages={[{ label: "Decoding", icon: "film" }, { label: "Sampling frames", icon: "image" }, { label: "Auto-labelling", icon: "cpu" }, { label: "Hash + dedup", icon: "link" }, { label: "Writing to Postgres", icon: "database" }]}
      models={allModels} modelStage={2} total={totalFrames} unit="frames" logLines={log} onDone={finishIngest} />;
  }
  if (stage === "done") {
    const cards = groups.map((g) => {
      const autoAcc = t.autoAccept ? Math.round(g.frames * 0.6) : 0;
      const conflicts = Math.round(g.frames * 0.11);
      return {
        icon: g.uc.icon, color: ucColor(g.uc), title: resolveDsName(g.uc), badge: g.uc.isNew ? "created" : null,
        sub: `${g.vs.length} video${g.vs.length !== 1 ? "s" : ""} · ${g.uc.label}`,
        stats: [{ v: "+" + g.frames.toLocaleString(), l: "frames", c: "var(--match)" }, ...(autoAcc ? [{ v: autoAcc.toLocaleString(), l: "auto-accepted", c: "var(--pred)" }] : []), { v: conflicts.toLocaleString(), l: "to review", c: "var(--gt)" }],
        openDsId: g.uc.dataset,
      };
    });
    return <DoneView title="Ingest complete" subtitle={`${totalFrames.toLocaleString()} frames split, auto-labelled, and committed across ${groups.length} dataset${groups.length !== 1 ? "s" : ""}.`}
      cards={cards} onReset={() => { setVideos([]); setStage("compose"); }} onExit={onExit} go={ctx.go} />;
  }

  return (
    <>
      <TopBar crumbs={[{ label: "New source", onClick: onExit }, { label: "Auto-label video" }]}>
        <span style={{ fontSize: 12, color: "var(--tx-2)" }}>{videos.length} video{videos.length !== 1 ? "s" : ""} · {tagged.length} tagged</span>
        <button className="btn" onClick={() => fileRef.current.click()}><Icon name="upload" size={15} />Add files</button>
        <input ref={fileRef} type="file" accept="video/*" multiple style={{ display: "none" }} onChange={onFiles} />
        <button className="btn primary" disabled={!tagged.length} onClick={() => setStage("processing")} style={{ opacity: tagged.length ? 1 : 0.45, cursor: tagged.length ? "pointer" : "not-allowed" }}><Icon name="sparkle" size={15} />Send to sensVeridian</button>
      </TopBar>
      <div style={{ flex: 1, display: "flex", minHeight: 0 }}>
        <div className="scroll" style={{ flex: 1, padding: "20px 24px" }}>
          <div style={{ maxWidth: 820, margin: "0 auto" }}>
            {videos.length === 0 ? <DropZone onBrowse={() => fileRef.current.click()} onSamples={addSamples} big label="Drop video files to ingest" sample="load sample clips" /> : (
              <>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 14 }}>
                  <div style={{ fontSize: 12, fontWeight: 600, color: "var(--tx-2)", textTransform: "uppercase", letterSpacing: ".06em" }}>Source videos</div>
                  <div style={{ flex: 1 }} />
                  <span style={{ fontSize: 11.5, color: "var(--tx-2)" }}>Sample all at</span>
                  <div style={{ display: "flex", gap: 4 }}>{SAMPLE_MODES.slice(0, 4).map((m) => <button key={m.id} className="btn sm" onClick={() => setAllMode(m.id)} style={{ padding: "4px 9px", color: "var(--tx-1)" }}>{m.label}</button>)}</div>
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{videos.map((v) => <VideoRow key={v.key} v={v} useCases={useCases} update={update} remove={remove} onAddTag={() => setAddTagFor(v.key)} />)}</div>
                <DropZone onBrowse={() => fileRef.current.click()} onSamples={addSamples} label="Drop more videos" sample="samples" />
              </>
            )}
          </div>
        </div>
        <PlanPanel groups={groups} untagged={untagged} totalFrames={totalFrames} onStart={() => setStage("processing")} onAddTag={() => setAddTagFor("__global")} t={t} setTweak={setTweak} />
      </div>
      {addTagFor !== null && <AddTagModal existing={useCases} onClose={() => setAddTagFor(null)} onCreate={createCustomCase} />}
    </>
  );
}

function DropZone({ onBrowse, onSamples, big, label, sample }) {
  const [over, setOver] = React.useState(false);
  return (
    <div onClick={onBrowse} onDragOver={(e) => { e.preventDefault(); setOver(true); }} onDragLeave={() => setOver(false)} onDrop={(e) => { e.preventDefault(); setOver(false); onSamples && onSamples(); }}
      style={{ border: "1.5px dashed " + (over ? "var(--accent)" : "var(--line-2)"), background: over ? "var(--accent-dim)" : "var(--bg-1)", borderRadius: 12, padding: big ? "56px 24px" : "22px 24px", textAlign: "center", cursor: "pointer", marginTop: big ? 0 : 14, transition: "border-color .12s, background .12s" }}>
      <div style={{ width: big ? 56 : 40, height: big ? 56 : 40, margin: "0 auto", borderRadius: 14, background: "var(--bg-3)", border: "1px solid var(--line-2)", display: "grid", placeItems: "center", color: "var(--accent-2)" }}><Icon name="upload" size={big ? 26 : 20} /></div>
      <div style={{ fontSize: big ? 16 : 13.5, fontWeight: 600, marginTop: big ? 16 : 10 }}>{label || "Drop files"}</div>
      <div style={{ fontSize: 12, color: "var(--tx-2)", marginTop: 4 }}>or <button onClick={(e) => { e.stopPropagation(); onBrowse(); }} style={{ color: "var(--accent-2)", fontWeight: 600 }}>browse</button>{sample && onSamples && <> · <button onClick={(e) => { e.stopPropagation(); onSamples(); }} style={{ color: "var(--accent-2)", fontWeight: 600 }}>{sample}</button></>}</div>
    </div>
  );
}

function VideoPoster({ v, w, h }) {
  return (
    <div style={{ position: "relative", width: w, height: h, borderRadius: 7, overflow: "hidden", background: "var(--bg-canvas)", flexShrink: 0, border: "1px solid var(--line)" }}>
      {v.url ? <video src={v.url} muted preload="metadata" style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <Scene image={v.poster} style={{ width: "100%", height: "100%" }} />}
      <div style={{ position: "absolute", inset: 0, background: "linear-gradient(180deg, rgba(7,9,13,.1), rgba(7,9,13,.55))" }} />
      <div style={{ position: "absolute", bottom: 4, right: 5, fontSize: 10, fontWeight: 600, fontFamily: "var(--mono)", color: "#eef2f7", background: "rgba(7,9,13,.6)", padding: "0 5px", borderRadius: 3 }}>{fmtDur(v.dur)}</div>
      <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: 26, height: 26, borderRadius: "50%", background: "rgba(7,9,13,.5)", border: "1px solid rgba(255,255,255,.3)", display: "grid", placeItems: "center" }}><svg width="10" height="10" viewBox="0 0 10 10"><path d="M2 1l7 4-7 4z" fill="#eef2f7" /></svg></div>
    </div>
  );
}

function VideoRow({ v, useCases, update, remove, onAddTag }) {
  const uc = useCases.find((u) => u.id === v.uc);
  const frames = estFrames(v.dur, v.mode);
  return (
    <div className="card" style={{ padding: 12, display: "flex", gap: 14, alignItems: "center", borderColor: uc ? "var(--line-2)" : "var(--line)" }}>
      <VideoPoster v={v} w={108} h={68} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span className="mono" style={{ fontSize: 13, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{v.name}</span>
          <div style={{ flex: 1 }} />
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <Icon name="image" size={13} style={{ color: "var(--tx-3)" }} />
            <select value={v.mode} onChange={(e) => update(v.key, { mode: e.target.value })} style={{ background: "var(--bg-3)", border: "1px solid var(--line-2)", borderRadius: 6, color: "var(--tx-0)", padding: "4px 7px", fontSize: 11.5 }}>{SAMPLE_MODES.map((m) => <option key={m.id} value={m.id}>{m.label}</option>)}</select>
          </div>
          <button className="btn ghost icon" onClick={() => remove(v.key)} style={{ padding: 4, color: "var(--tx-3)" }} title="Remove"><Icon name="x" size={14} /></button>
        </div>
        <div style={{ display: "flex", gap: 12, fontSize: 11, color: "var(--tx-2)", marginTop: 3 }} className="mono">
          <span>{v.w}×{v.h}</span><span>{fmtDur(v.dur)}</span><span>{v.size} MB</span><span style={{ color: "var(--accent-2)" }}>≈ {frames.toLocaleString()} frames</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 9, flexWrap: "wrap" }}>
          <span style={{ fontSize: 11, color: "var(--tx-2)" }}>Use-case</span>
          {useCases.map((u) => {
            const on = v.uc === u.id;
            return <button key={u.id} onClick={() => update(v.key, { uc: u.id, palette: u.palette, poster: posterFor(u.palette, v.key.length + u.id.length) })} title={u.label}
              style={{ display: "flex", alignItems: "center", gap: 5, padding: "4px 9px", borderRadius: 6, fontSize: 11.5, fontWeight: 500, border: "1px solid " + (on ? ucColor(u) : "var(--line-2)"), background: on ? "var(--bg-3)" : "transparent", color: on ? "var(--tx-0)" : "var(--tx-2)", maxWidth: 150, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              <Icon name={u.icon} size={12} />{u.label.split(" / ")[0]}{u.isNew && <span style={{ color: ucColor(u), fontSize: 9 }}>●</span>}</button>;
          })}
          <button onClick={onAddTag} title="Create a new use-case tag" style={{ display: "flex", alignItems: "center", gap: 4, padding: "4px 9px", borderRadius: 6, fontSize: 11.5, fontWeight: 500, border: "1px dashed var(--line-2)", background: "transparent", color: "var(--accent-2)" }}><Icon name="plus" size={12} />New tag</button>
        </div>
      </div>
      {uc ? (
        <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 6, paddingLeft: 12, borderLeft: "1px solid var(--line)", minWidth: 138 }}>
          <span style={{ fontSize: 10.5, color: "var(--tx-2)" }}>auto-label with</span>
          <div style={{ display: "flex", gap: 4, flexWrap: "wrap", justifyContent: "flex-end" }}>{uc.models.map((m) => <ModelChip key={m} id={m} size="sm" />)}</div>
          <span style={{ fontSize: 10.5, color: "var(--tx-2)", display: "flex", alignItems: "center", gap: 4, textAlign: "right" }}><Icon name={uc.isNew ? "plus" : "arrowR"} size={11} />{resolveDsName(uc).split(" — ")[0]}</span>
        </div>
      ) : (
        <div style={{ paddingLeft: 12, borderLeft: "1px solid var(--line)", minWidth: 138, display: "flex", alignItems: "center", gap: 6, color: "var(--gt)", fontSize: 11.5 }}><Icon name="alert" size={14} />Needs a tag</div>
      )}
    </div>
  );
}

function PlanPanel({ groups, untagged, totalFrames, onStart, onAddTag, t, setTweak }) {
  return (
    <div style={{ width: 320, flexShrink: 0, borderLeft: "1px solid var(--line)", background: "var(--bg-1)", display: "flex", flexDirection: "column" }}>
      <div style={{ padding: "14px 16px", borderBottom: "1px solid var(--line)", display: "flex", alignItems: "center", gap: 10 }}>
        <div style={{ flex: 1 }}><div style={{ fontWeight: 700, fontSize: 14 }}>Ingest plan</div><div style={{ fontSize: 11.5, color: "var(--tx-2)", marginTop: 2 }}>Each tag combines into one dataset.</div></div>
        <button className="btn sm" onClick={onAddTag}><Icon name="plus" size={13} />Tag</button>
      </div>
      <div className="scroll" style={{ flex: 1, padding: 14, display: "flex", flexDirection: "column", gap: 12 }}>
        {groups.length === 0 && <div style={{ color: "var(--tx-2)", fontSize: 12.5, textAlign: "center", padding: "30px 10px" }}>Tag a video with a use-case to build the plan.</div>}
        {groups.map((g) => {
          const isNew = g.uc.isNew;
          return (
            <div key={g.uc.id} className="card" style={{ padding: 12, background: "var(--bg-2)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <div style={{ width: 26, height: 26, borderRadius: 7, background: "var(--bg-3)", display: "grid", placeItems: "center", color: ucColor(g.uc) }}><Icon name={g.uc.icon} size={15} /></div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 12.5, fontWeight: 600, display: "flex", alignItems: "center", gap: 6 }}>{g.uc.label}{isNew && <span className="chip" style={{ padding: "0 6px", fontSize: 9, borderColor: ucColor(g.uc), color: ucColor(g.uc) }}>new</span>}</div>
                  <div style={{ fontSize: 10.5, color: "var(--tx-2)" }}>{g.vs.length} video{g.vs.length !== 1 ? "s" : ""} · ≈ {g.frames.toLocaleString()} frames</div>
                </div>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 10, paddingTop: 10, borderTop: "1px solid var(--line)" }}><span style={{ fontSize: 10.5, color: "var(--tx-2)" }}>label</span>{g.uc.models.map((m) => <ModelChip key={m} id={m} size="sm" />)}</div>
              <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 8, fontSize: 11 }}>
                <Icon name={isNew ? "plus" : "arrowR"} size={12} style={{ color: isNew ? ucColor(g.uc) : "var(--tx-3)" }} />
                <span style={{ color: "var(--tx-1)" }}>{isNew ? "create dataset" : "append to"}</span>
                <span style={{ fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{resolveDsName(g.uc).split(" — ")[0]}</span>
              </div>
            </div>
          );
        })}
        {/* confidence-gated pre-labeling */}
        <TrustControl t={t} setTweak={setTweak} totalFrames={totalFrames} />
      </div>
      <div style={{ padding: 14, borderTop: "1px solid var(--line)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 6 }}><span style={{ color: "var(--tx-2)" }}>Total frames</span><span className="tnum" style={{ fontWeight: 700 }}>≈ {totalFrames.toLocaleString()}</span></div>
        <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 12 }}><span style={{ color: "var(--tx-2)" }}>Datasets touched</span><span className="tnum" style={{ fontWeight: 700 }}>{groups.length}</span></div>
        {untagged > 0 && <div style={{ fontSize: 11, color: "var(--gt)", marginBottom: 10, display: "flex", alignItems: "center", gap: 6 }}><Icon name="alert" size={13} />{untagged} untagged video{untagged !== 1 ? "s" : ""} will be skipped</div>}
        <button className="btn primary" onClick={onStart} disabled={!groups.length} style={{ width: "100%", justifyContent: "center", opacity: groups.length ? 1 : 0.45, cursor: groups.length ? "pointer" : "not-allowed" }}><Icon name="sparkle" size={15} />Send to sensVeridian</button>
        <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 10, fontSize: 10.5, color: "var(--tx-3)", justifyContent: "center" }}><Icon name="database" size={12} style={{ color: "var(--match)" }} />writes to {window.VD.storage.engine}</div>
      </div>
    </div>
  );
}

/* confidence-gated pre-labeling control (idea #2) */
function TrustControl({ t, setTweak, totalFrames }) {
  const reviewFrac = Math.max(0.06, Math.min(0.9, 1 - (t.trustThreshold - 0.3) * 1.05));
  const reviewN = Math.round(totalFrames * (t.autoAccept ? reviewFrac : 1));
  return (
    <div className="card" style={{ padding: 12, background: "var(--bg-2)", borderColor: t.autoAccept ? "var(--pred)" : "var(--line)" }}>
      <button onClick={() => setTweak("autoAccept", !t.autoAccept)} style={{ display: "flex", alignItems: "center", gap: 9, width: "100%", textAlign: "left" }}>
        <span style={{ width: 30, height: 17, borderRadius: 999, background: t.autoAccept ? "var(--pred)" : "var(--bg-3)", border: "1px solid " + (t.autoAccept ? "var(--pred)" : "var(--line-2)"), position: "relative", flexShrink: 0 }}><span style={{ position: "absolute", top: 1, left: t.autoAccept ? 14 : 1, width: 13, height: 13, borderRadius: "50%", background: t.autoAccept ? "#07090d" : "var(--tx-2)", transition: "left .12s" }} /></span>
        <div style={{ flex: 1 }}><div style={{ fontSize: 12.5, fontWeight: 600, display: "flex", alignItems: "center", gap: 6 }}><Icon name="spark" size={13} style={{ color: "var(--pred)" }} />Confidence-gated pre-labeling</div></div>
      </button>
      <div style={{ fontSize: 11, color: "var(--tx-2)", marginTop: 6, lineHeight: 1.45 }}>Auto-accept detections above the trust threshold when models agree. You only review the rest.</div>
      {t.autoAccept && (
        <div style={{ marginTop: 10 }}>
          <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, marginBottom: 5 }}><span style={{ color: "var(--tx-2)" }}>Trust ≥</span><span className="mono tnum" style={{ color: "var(--pred)" }}>{t.trustThreshold.toFixed(2)}</span></div>
          <input type="range" min={0.5} max={0.98} step={0.01} value={t.trustThreshold} onChange={(e) => setTweak("trustThreshold", +e.target.value)} style={{ width: "100%", accentColor: "var(--pred)" }} />
          <div style={{ marginTop: 8, padding: "8px 10px", background: "var(--bg-1)", borderRadius: 7, fontSize: 11.5, display: "flex", alignItems: "center", gap: 7 }}>
            <Icon name="spark" size={14} style={{ color: "var(--match)" }} />
            <span>review only <b className="tnum" style={{ color: "var(--match)" }}>{Math.round(reviewFrac * 100)}%</b> <span style={{ color: "var(--tx-2)" }}>≈ {reviewN.toLocaleString()} frames</span></span>
          </div>
        </div>
      )}
    </div>
  );
}

/* ============================ ADD TAG MODAL ============================== */
const TAG_ICONS = ["tag", "car", "face", "qr", "ruler", "box", "layers", "cpu"];
function AddTagModal({ existing, onClose, onCreate }) {
  const [label, setLabel] = React.useState("");
  const [models, setModels] = React.useState([]);
  const [icon, setIcon] = React.useState("tag");
  const inputRef = React.useRef(null);
  React.useEffect(() => { inputRef.current && inputRef.current.focus(); }, []);
  const toggleModel = (id) => setModels((ms) => {
    let next; if (ms.includes(id)) { next = ms.filter((m) => m !== id); if (id === "fd") next = next.filter((m) => m !== "fr"); }
    else { next = [...ms, id]; if (id === "fr" && !next.includes("fd")) next.push("fd"); }
    return ["amod", "qrcode", "fd", "fr", "aed"].filter((m) => next.includes(m));
  });
  const slug = label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 24);
  const collision = existing.some((u) => u.label.toLowerCase() === label.trim().toLowerCase());
  const valid = label.trim().length >= 2 && models.length > 0 && !collision;
  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, background: "rgba(4,6,10,.66)", backdropFilter: "blur(3px)", zIndex: 90, display: "grid", placeItems: "center" }} className="fade">
      <div onClick={(e) => e.stopPropagation()} className="card pop" style={{ width: 480, maxWidth: "92vw", boxShadow: "var(--shadow-pop)" }}>
        <div style={{ padding: "16px 20px", borderBottom: "1px solid var(--line)", display: "flex", alignItems: "center", gap: 10 }}><Icon name="tag" size={18} style={{ color: "var(--accent)" }} /><div style={{ fontWeight: 700, fontSize: 15 }}>New use-case tag</div><div style={{ flex: 1 }} /><button className="btn ghost icon" onClick={onClose}><Icon name="x" size={16} /></button></div>
        <div style={{ padding: 20, display: "flex", flexDirection: "column", gap: 18 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: "var(--tx-2)", textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8 }}>Tag name</div>
            <div style={{ display: "flex", gap: 10 }}>
              <select value={icon} onChange={(e) => setIcon(e.target.value)} style={{ background: "var(--bg-3)", border: "1px solid var(--line-2)", borderRadius: 7, color: "var(--tx-0)", padding: "0 8px", fontSize: 12 }} aria-label="icon">{TAG_ICONS.map((ic) => <option key={ic} value={ic}>{ic}</option>)}</select>
              <div style={{ flex: 1, display: "flex", alignItems: "center", gap: 8, background: "var(--bg-2)", border: "1px solid " + (collision ? "var(--conflict)" : "var(--line-2)"), borderRadius: 7, padding: "0 10px" }}>
                <Icon name={icon} size={15} style={{ color: "var(--accent-2)" }} />
                <input ref={inputRef} value={label} onChange={(e) => setLabel(e.target.value)} placeholder="e.g. Retail / Shelf-stock" onKeyDown={(e) => { if (e.key === "Enter" && valid) onCreate({ label: label.trim(), models, icon }); }} style={{ flex: 1, background: "transparent", border: "none", color: "var(--tx-0)", fontSize: 13.5, padding: "9px 0", outline: "none" }} />
              </div>
            </div>
            {collision && <div style={{ fontSize: 11, color: "var(--conflict)", marginTop: 6 }}>A tag with this name already exists.</div>}
          </div>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: "var(--tx-2)", textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8 }}>Auto-label with</div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
              {window.VD.models.map((m) => {
                const on = models.includes(m.id);
                return <button key={m.id} onClick={() => toggleModel(m.id)} style={{ display: "flex", alignItems: "center", gap: 9, padding: "9px 11px", borderRadius: 8, textAlign: "left", border: "1px solid " + (on ? vhelp.modelColor(m.id) : "var(--line-2)"), background: on ? "var(--bg-3)" : "var(--bg-2)" }}>
                  <span style={{ width: 16, height: 16, borderRadius: 4, border: "1px solid " + (on ? vhelp.modelColor(m.id) : "var(--line-2)"), background: on ? vhelp.modelColor(m.id) : "transparent", display: "grid", placeItems: "center", color: "#07090d", flexShrink: 0 }}>{on && <Icon name="check" size={12} stroke={2.4} />}</span>
                  <div style={{ minWidth: 0 }}><div style={{ fontSize: 12.5, fontWeight: 600 }}>{m.short}{m.depends_on && <span style={{ fontSize: 9.5, color: "var(--tx-3)", fontWeight: 400 }}> · needs FD</span>}</div><div style={{ fontSize: 10, color: "var(--tx-2)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{m.display_name}</div></div>
                </button>;
              })}
            </div>
          </div>
          <div style={{ background: "var(--bg-2)", border: "1px solid var(--line)", borderRadius: 8, padding: "10px 12px", display: "flex", alignItems: "center", gap: 8, fontSize: 11.5, color: "var(--tx-2)" }}><Icon name="database" size={14} style={{ color: "var(--match)" }} />Creates dataset <span className="mono" style={{ color: "var(--tx-0)" }}>{slug || "…"}</span>, auto-labelled by {models.length ? models.map((m) => window.VD.models.find((x) => x.id === m).short).join(" + ") : "—"}.</div>
        </div>
        <div style={{ padding: "13px 20px", borderTop: "1px solid var(--line)", display: "flex", alignItems: "center", gap: 10 }}><div style={{ flex: 1 }} /><button className="btn ghost" onClick={onClose}>Cancel</button><button className="btn primary" disabled={!valid} onClick={() => onCreate({ label: label.trim(), models, icon })} style={{ opacity: valid ? 1 : 0.45, cursor: valid ? "pointer" : "not-allowed" }}><Icon name="plus" size={15} />Create tag</button></div>
      </div>
    </div>
  );
}

/* ===================== SHARED PIPELINE + DONE (reusable) ================= */
function ProcessingView({ title, subtitle, stages, models, modelStage, total, unit, logLines, onDone }) {
  const [prog, setProg] = React.useState(0);
  const [log, setLog] = React.useState([]);
  const logRef = React.useRef(null);
  React.useEffect(() => {
    let i = 0; const li = setInterval(() => { if (i < logLines.length) { setLog((l) => [...l, logLines[i]]); i++; } }, 380);
    const pi = setInterval(() => setProg((p) => Math.min(100, p + 1.6)), 70);
    return () => { clearInterval(li); clearInterval(pi); };
  }, []);
  React.useEffect(() => { if (prog >= 100) { const t = setTimeout(onDone, 700); return () => clearTimeout(t); } }, [prog]);
  React.useEffect(() => { if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight; }, [log]);
  const curStage = Math.min(stages.length - 1, Math.floor((prog / 100) * stages.length));
  const itemsDone = Math.round((prog / 100) * total);
  const mStage = modelStage == null ? -1 : modelStage;
  return (
    <>
      <TopBar crumbs={[{ label: "New source" }, { label: "Processing" }]} />
      <div style={{ flex: 1, display: "grid", placeItems: "center", padding: 24, overflow: "auto" }}>
        <div style={{ width: 720, maxWidth: "100%" }}>
          <div style={{ textAlign: "center", marginBottom: 26 }}><div style={{ fontSize: 19, fontWeight: 700 }}>{title}</div><div style={{ fontSize: 13, color: "var(--tx-2)", marginTop: 4 }}>{subtitle}</div></div>
          <div style={{ display: "flex", alignItems: "center", marginBottom: 24 }}>
            {stages.map((s, i) => (
              <React.Fragment key={s.label}>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 7, flex: "0 0 auto" }}>
                  <div style={{ width: 40, height: 40, borderRadius: "50%", display: "grid", placeItems: "center", border: "2px solid " + (i < curStage ? "var(--match)" : i === curStage ? "var(--accent)" : "var(--line-2)"), background: i < curStage ? "var(--match-soft)" : i === curStage ? "var(--accent-dim)" : "var(--bg-1)", color: i < curStage ? "var(--match)" : i === curStage ? "var(--accent-2)" : "var(--tx-3)", transition: "all .3s" }}>{i < curStage ? <Icon name="check" size={18} /> : <Icon name={s.icon} size={17} />}</div>
                  <span style={{ fontSize: 10.5, color: i <= curStage ? "var(--tx-1)" : "var(--tx-3)", whiteSpace: "nowrap", fontWeight: i === curStage ? 600 : 400 }}>{s.label}</span>
                </div>
                {i < stages.length - 1 && <div style={{ flex: 1, height: 2, background: i < curStage ? "var(--match)" : "var(--line-2)", margin: "0 4px", marginBottom: 22, transition: "background .3s" }} />}
              </React.Fragment>
            ))}
          </div>
          <div className="card" style={{ padding: 16, marginBottom: 14 }}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8, fontSize: 12.5 }}><span style={{ fontWeight: 600 }}>{stages[curStage].label}…</span><span className="mono tnum" style={{ color: "var(--accent-2)" }}>{itemsDone.toLocaleString()} / {total.toLocaleString()} {unit}</span></div>
            <div className="meter" style={{ height: 8 }}><i style={{ width: prog + "%", background: "linear-gradient(90deg,var(--accent),var(--accent-2))", transition: "width .1s" }} /></div>
            {models && models.length > 0 && (
              <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
                {models.map((m) => { const lit = curStage >= mStage; return <span key={m} className="chip" style={{ borderColor: lit ? vhelp.modelColor(m) : "var(--line)", background: lit ? "var(--bg-2)" : "transparent", opacity: lit ? 1 : 0.5 }}><span className="dot" style={{ background: vhelp.modelColor(m), boxShadow: lit ? `0 0 6px ${vhelp.modelColor(m)}` : "none" }} />{window.VD.models.find((x) => x.id === m)?.short || m}{lit && curStage === mStage ? " · inferring" : ""}</span>; })}
              </div>
            )}
          </div>
          <div ref={logRef} className="card scroll" style={{ height: 150, padding: "10px 14px", fontFamily: "var(--mono)", fontSize: 11.5, lineHeight: 1.7, background: "var(--bg-canvas)" }}>
            {log.map((l, i) => <div key={i} className="fade" style={{ color: l.startsWith("✓") ? "var(--match)" : l.startsWith("»") ? "var(--tx-1)" : "var(--tx-2)" }}>{l}</div>)}
            {prog < 100 && <span style={{ color: "var(--accent-2)" }}>▌</span>}
          </div>
        </div>
      </div>
    </>
  );
}

function DoneView({ title, subtitle, cards, onReset, onExit, go }) {
  return (
    <>
      <TopBar crumbs={[{ label: "New source", onClick: onExit }, { label: "Complete" }]}><button className="btn" onClick={onReset}><Icon name="plus" size={15} />New source</button></TopBar>
      <div className="scroll" style={{ flex: 1, padding: 24 }}>
        <div style={{ maxWidth: 720, margin: "0 auto" }}>
          <div style={{ textAlign: "center", margin: "10px 0 26px" }}>
            <div style={{ width: 54, height: 54, margin: "0 auto 14px", borderRadius: "50%", background: "var(--match-soft)", border: "2px solid var(--match)", display: "grid", placeItems: "center", color: "var(--match)" }}><Icon name="check" size={28} /></div>
            <div style={{ fontSize: 20, fontWeight: 700 }}>{title}</div><div style={{ fontSize: 13.5, color: "var(--tx-2)", marginTop: 4 }}>{subtitle}</div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {cards.map((c, i) => (
              <div key={i} className="card" style={{ padding: 16, display: "flex", alignItems: "center", gap: 16 }}>
                <div style={{ width: 44, height: 44, borderRadius: 10, background: "var(--bg-2)", display: "grid", placeItems: "center", color: c.color }}><Icon name={c.icon} size={22} /></div>
                <div style={{ flex: 1, minWidth: 0 }}><div style={{ fontWeight: 700, fontSize: 14.5, display: "flex", alignItems: "center", gap: 8 }}>{c.title}{c.badge && <span className="chip" style={{ padding: "0 7px", fontSize: 9.5, borderColor: "var(--match)", color: "var(--match)" }}>{c.badge}</span>}</div><div style={{ fontSize: 12, color: "var(--tx-2)", marginTop: 2 }}>{c.sub}</div></div>
                <div style={{ display: "flex", gap: 20, textAlign: "right" }}>{c.stats.map((s, j) => <div key={j}><div className="tnum" style={{ fontSize: 16, fontWeight: 700, color: s.c }}>{s.v}</div><div style={{ fontSize: 10, color: "var(--tx-2)" }}>{s.l}</div></div>)}</div>
                <button className="btn primary sm" disabled={!c.openDsId} onClick={() => c.openDsId && go({ name: "grid", datasetId: c.openDsId })} style={{ opacity: c.openDsId ? 1 : 0.5 }}>Open dataset<Icon name="arrowR" size={14} /></button>
              </div>
            ))}
          </div>
          <div style={{ display: "flex", justifyContent: "center", gap: 10, marginTop: 24 }}><button className="btn" onClick={onReset}><Icon name="upload" size={15} />Add another source</button><button className="btn" onClick={() => go({ name: "datasets" })}><Icon name="folder" size={15} />All datasets</button></div>
        </div>
      </div>
    </>
  );
}

/* ===================== LOCAL DATASET FOLDER FLOW ========================= */
function localSlug(name) {
  return (name || "dataset").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 32) || "dataset";
}
function defaultModelsFor(entry) {
  const n = (entry.name || "").toLowerCase();
  if (entry.kind === "video") return ["amod"];
  if (n.includes("qr") || n.includes("barcode")) return ["qrcode"];
  if (n.includes("face") || n.includes("fr")) return ["fd"];
  if (n.includes("ppe") || n.includes("hard") || n.includes("person") || n.includes("hat")) return ["amod"];
  return ["amod"];
}

function LocalIngestFlow({ onExit }) {
  const ctx = React.useContext(VDCtx);
  const { t, setTweak } = ctx;
  const [entries, setEntries] = React.useState(null);     // null = loading
  const [err, setErr] = React.useState(null);
  const [sel, setSel] = React.useState({});               // path -> { models, maxImages }
  const [stage, setStage] = React.useState("compose");    // compose | processing | done
  const [job, setJob] = React.useState(null);
  const [created, setCreated] = React.useState([]);
  const [mode, setMode] = React.useState("eval");         // eval (read-only) | curate (writes labels)
  const [reingest, setReingest] = React.useState(false);  // re-run + overwrite existing predictions

  React.useEffect(() => {
    let alive = true;
    window.VeridianAPI.browseDatasets()
      .then((r) => { if (alive) setEntries((r && r.entries) || []); })
      .catch((e) => { if (alive) setErr(String(e)); });
    return () => { alive = false; };
  }, []);

  const toggle = (e) => setSel((s) => {
    const next = { ...s };
    if (next[e.path]) delete next[e.path];
    else next[e.path] = { models: defaultModelsFor(e), maxImages: 200 };
    return next;
  });
  const setModels = (path, models) => setSel((s) => ({ ...s, [path]: { ...s[path], models } }));
  const setMax = (path, n) => setSel((s) => ({ ...s, [path]: { ...s[path], maxImages: Math.max(1, n || 1) } }));
  const toggleModel = (path, id) => setSel((s) => {
    const cur = (s[path] && s[path].models) || [];
    let next = cur.includes(id) ? cur.filter((m) => m !== id) : [...cur, id];
    if (id === "fr" && next.includes("fr") && !next.includes("fd")) next.push("fd");      // FR needs FD
    if (id === "fd" && !next.includes("fd")) next = next.filter((m) => m !== "fr");
    next = ["amod", "qrcode", "fd", "fr", "aed"].filter((m) => next.includes(m));
    return { ...s, [path]: { ...s[path], models: next } };
  });

  const selected = (entries || []).filter((e) => sel[e.path]);
  const canLaunch = selected.length && selected.every((e) => (sel[e.path].models || []).length);

  const launch = async () => {
    const groups = selected.map((e) => {
      const c = sel[e.path];
      const dsId = localSlug(e.name);
      const frames = e.kind === "video" ? Math.max(1, e.videos * 60) : Math.min(c.maxImages, e.images || c.maxImages);
      return { tag: dsId, label: e.name, models: c.models, path: e.path, dataset: dsId,
               isNew: true, maxImages: c.maxImages, kind: e.kind === "video" ? "video" : "image",
               mode, reingest, frames };
    });
    const spec = { source: "local", trustThreshold: t.autoAccept ? t.trustThreshold : null, groups };
    try {
      const handle = await window.VeridianAPI.createIngestJob(spec);
      setJob({ jobId: handle.jobId, groups });
      setCreated(groups.map((g) => g.dataset));
      setStage("processing");
    } catch (e) { setErr(String(e)); }
  };

  if (stage === "processing" && job) {
    return <LiveProcessing job={job} onDone={() => setStage("done")} />;
  }
  if (stage === "done") {
    const cards = created.map((id) => {
      const d = window.VD.getDataset(id);
      return { icon: "folder", color: "var(--m-amod)", title: (d && d.name) || id, badge: "created",
               sub: "local ingest · models run", stats: [{ v: "+" + ((d && d.count) || 0), l: "images", c: "var(--match)" }], openDsId: id };
    });
    return <DoneView title="Ingest complete" subtitle={`Ran the oracle models over ${created.length} folder${created.length !== 1 ? "s" : ""}.`}
      cards={cards} onReset={() => { setSel({}); setJob(null); setCreated([]); setStage("compose"); }} onExit={onExit} go={ctx.go} />;
  }

  return (
    <>
      <TopBar crumbs={[{ label: "New source", onClick: onExit }, { label: "Local dataset folder" }]}>
        <span style={{ fontSize: 12, color: "var(--tx-2)" }}>{selected.length} selected</span>
        <button className="btn primary" disabled={!canLaunch} onClick={launch}
          style={{ opacity: canLaunch ? 1 : 0.45, cursor: canLaunch ? "pointer" : "not-allowed" }}>
          <Icon name="sparkle" size={15} />Run models</button>
      </TopBar>
      <div style={{ flex: 1, display: "flex", minHeight: 0 }}>
        <div className="scroll" style={{ flex: 1, padding: "20px 24px" }}>
          <div style={{ maxWidth: 880, margin: "0 auto" }}>
            <div style={{ fontSize: 13, color: "var(--tx-1)", marginBottom: 14 }}>
              Folders under the datasets root. Select one or more, choose models, then run the oracles.
            </div>
            {err && <div className="card" style={{ padding: 12, borderColor: "var(--conflict)", color: "var(--conflict)", marginBottom: 12 }}><Icon name="alert" size={14} /> {err}</div>}
            {entries === null && <div style={{ color: "var(--tx-2)", padding: 30, textAlign: "center" }}>Scanning datasets root…</div>}
            {entries && entries.length === 0 && <div style={{ color: "var(--tx-2)", padding: 30, textAlign: "center" }}>No image/video folders found under the datasets root.</div>}
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {(entries || []).map((e) => {
                const on = !!sel[e.path];
                const cfg = sel[e.path] || {};
                return (
                  <div key={e.path} className="card" style={{ padding: 12, borderColor: on ? "var(--accent)" : "var(--line)" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                      <button onClick={() => toggle(e)} style={{ width: 18, height: 18, borderRadius: 4, border: "1px solid " + (on ? "var(--accent)" : "var(--line-2)"), background: on ? "var(--accent)" : "transparent", display: "grid", placeItems: "center", color: "#07090d", flexShrink: 0 }}>{on && <Icon name="check" size={12} stroke={2.4} />}</button>
                      <Icon name={e.kind === "video" ? "film" : "folder"} size={18} style={{ color: "var(--tx-2)" }} />
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontWeight: 600, fontSize: 13.5 }}>{e.name}</div>
                        <div className="mono" style={{ fontSize: 10.5, color: "var(--tx-2)" }}>
                          {e.images ? `${e.images.toLocaleString()} images` : ""}{e.images && e.videos ? " · " : ""}{e.videos ? `${e.videos} videos` : ""}{e.has_labels ? " · labels" : ""}
                        </div>
                      </div>
                    </div>
                    {on && (
                      <div style={{ marginTop: 10, paddingTop: 10, borderTop: "1px solid var(--line)", display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" }}>
                        <span style={{ fontSize: 11, color: "var(--tx-2)" }}>models</span>
                        {window.VD.models.map((m) => {
                          const active = (cfg.models || []).includes(m.id);
                          return <button key={m.id} onClick={() => toggleModel(e.path, m.id)} title={m.display_name}
                            style={{ padding: "3px 9px", borderRadius: 6, fontSize: 11.5, fontWeight: 600, border: "1px solid " + (active ? vhelp.modelColor(m.id) : "var(--line-2)"), background: active ? "var(--bg-3)" : "transparent", color: active ? "var(--tx-0)" : "var(--tx-2)" }}>{m.short}</button>;
                        })}
                        {e.kind !== "video" && (
                          <span style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 6, fontSize: 11, color: "var(--tx-2)" }}>
                            max images
                            <input type="number" min={1} value={cfg.maxImages} onChange={(ev) => setMax(e.path, parseInt(ev.target.value, 10))}
                              style={{ width: 72, background: "var(--bg-3)", border: "1px solid var(--line-2)", borderRadius: 6, color: "var(--tx-0)", padding: "4px 7px", fontSize: 11.5 }} />
                          </span>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
        <div style={{ width: 300, flexShrink: 0, borderLeft: "1px solid var(--line)", background: "var(--bg-1)", padding: 14, display: "flex", flexDirection: "column", gap: 12 }}>
          <div style={{ fontWeight: 700, fontSize: 14 }}>Run plan</div>
          <div style={{ fontSize: 11.5, color: "var(--tx-2)" }}>Each selected folder becomes a dataset; the oracle models run over its images (videos are frame-split first).</div>
          <TrustControl t={t} setTweak={setTweak} totalFrames={selected.reduce((s, e) => s + (e.kind === "video" ? 0 : Math.min((sel[e.path] || {}).maxImages || 0, e.images || 0)), 0)} />
          <div style={{ borderTop: "1px solid var(--line)", paddingTop: 12 }}>
            <div style={{ fontSize: 11, color: "var(--tx-2)", marginBottom: 6 }}>Ingest path</div>
            <div style={{ display: "flex", gap: 6 }}>
              {[["eval", "Evaluate", "shield", "Read-only · score predictions vs ground-truth"], ["curate", "Curate", "edit", "Verify writes corrected labels back to disk (.bak kept)"]].map(([id, lab, ic, tip]) => (
                <button key={id} title={tip} onClick={() => setMode(id)} className="btn sm" style={{ flex: 1, justifyContent: "center", background: mode === id ? "var(--bg-3)" : "transparent", border: "1px solid " + (mode === id ? (id === "curate" ? "var(--gt)" : "var(--accent)") : "var(--line-2)"), color: mode === id ? "var(--tx-0)" : "var(--tx-2)" }}>
                  <Icon name={ic} size={12} />{lab}
                </button>
              ))}
            </div>
            <label style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 10, fontSize: 11.5, color: "var(--tx-1)", cursor: "pointer" }}>
              <input type="checkbox" checked={reingest} onChange={(e) => setReingest(e.target.checked)} style={{ accentColor: "var(--accent)" }} />
              Re-run &amp; overwrite existing predictions
            </label>
          </div>
          <div style={{ flex: 1 }} />
          <button className="btn primary" disabled={!canLaunch} onClick={launch} style={{ justifyContent: "center", opacity: canLaunch ? 1 : 0.45, cursor: canLaunch ? "pointer" : "not-allowed" }}><Icon name="sparkle" size={15} />Run models</button>
          <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 10.5, color: "var(--tx-3)", justifyContent: "center" }}><Icon name="database" size={12} style={{ color: "var(--match)" }} />writes to PostgreSQL</div>
        </div>
      </div>
    </>
  );
}

/* live, WS-driven progress (real ingest job, not a timer simulation) */
function LiveProcessing({ job, onDone }) {
  const STAGE_ICONS = { "Decoding": "film", "Sampling frames": "image", "Auto-labelling": "cpu", "Hash + dedup": "link", "Writing to Postgres": "database" };
  const STAGE_ORDER = ["Decoding", "Sampling frames", "Auto-labelling", "Hash + dedup", "Writing to Postgres"];
  const [frame, setFrame] = React.useState({ stage: "Queued", progress: 0, framesDone: 0, framesTotal: 0, status: "queued" });
  const [log, setLog] = React.useState(["» job " + job.jobId + " queued"]);
  const logRef = React.useRef(null);
  const doneRef = React.useRef(false);

  React.useEffect(() => {
    const unsub = window.VeridianAPI.subscribeJob(job.jobId, (f) => {
      setFrame(f);
      setLog((l) => [...l.slice(-60), `» ${f.stage}  ${f.framesDone || 0}/${f.framesTotal || 0}${f.status === "error" ? "  ERROR: " + (f.error || "") : ""}`]);
      if ((f.status === "done" || f.status === "error") && !doneRef.current) {
        doneRef.current = true;
        Promise.all((job.groups || []).map((g) => (window.VD.ensureDataset ? window.VD.ensureDataset(g.dataset).catch(() => {}) : Promise.resolve())))
          .then(() => setTimeout(onDone, 600));
      }
    });
    return () => { try { unsub && unsub(); } catch (e) { /* noop */ } };
  }, []);
  React.useEffect(() => { if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight; }, [log]);

  const curStage = Math.max(0, STAGE_ORDER.indexOf(frame.stage));
  return (
    <>
      <TopBar crumbs={[{ label: "New source" }, { label: "Processing" }]} />
      <div style={{ flex: 1, display: "grid", placeItems: "center", padding: 24, overflow: "auto" }}>
        <div style={{ width: 720, maxWidth: "100%" }}>
          <div style={{ textAlign: "center", marginBottom: 26 }}>
            <div style={{ fontSize: 19, fontWeight: 700 }}>sensVeridian is running the models</div>
            <div style={{ fontSize: 13, color: "var(--tx-2)", marginTop: 4 }}>Live progress from the ingest worker over the WebSocket.</div>
          </div>
          <div style={{ display: "flex", alignItems: "center", marginBottom: 24 }}>
            {STAGE_ORDER.map((s, i) => (
              <React.Fragment key={s}>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 7 }}>
                  <div style={{ width: 40, height: 40, borderRadius: "50%", display: "grid", placeItems: "center", border: "2px solid " + (i < curStage ? "var(--match)" : i === curStage ? "var(--accent)" : "var(--line-2)"), background: i < curStage ? "var(--match-soft)" : i === curStage ? "var(--accent-dim)" : "var(--bg-1)", color: i < curStage ? "var(--match)" : i === curStage ? "var(--accent-2)" : "var(--tx-3)" }}>{i < curStage ? <Icon name="check" size={18} /> : <Icon name={STAGE_ICONS[s]} size={17} />}</div>
                  <span style={{ fontSize: 10.5, color: i <= curStage ? "var(--tx-1)" : "var(--tx-3)", whiteSpace: "nowrap", fontWeight: i === curStage ? 600 : 400 }}>{s}</span>
                </div>
                {i < STAGE_ORDER.length - 1 && <div style={{ flex: 1, height: 2, background: i < curStage ? "var(--match)" : "var(--line-2)", margin: "0 4px", marginBottom: 22 }} />}
              </React.Fragment>
            ))}
          </div>
          <div className="card" style={{ padding: 16, marginBottom: 14 }}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8, fontSize: 12.5 }}>
              <span style={{ fontWeight: 600 }}>{frame.stage}…</span>
              <span className="mono tnum" style={{ color: "var(--accent-2)" }}>{(frame.framesDone || 0).toLocaleString()} / {(frame.framesTotal || 0).toLocaleString()} frames</span>
            </div>
            <div className="meter" style={{ height: 8 }}><i style={{ width: (frame.progress || 0) + "%", background: frame.status === "error" ? "var(--conflict)" : "linear-gradient(90deg,var(--accent),var(--accent-2))", transition: "width .2s" }} /></div>
          </div>
          <div ref={logRef} className="card scroll" style={{ height: 170, padding: "10px 14px", fontFamily: "var(--mono)", fontSize: 11.5, lineHeight: 1.7, background: "var(--bg-canvas)" }}>
            {log.map((l, i) => <div key={i} style={{ color: l.includes("ERROR") ? "var(--conflict)" : "var(--tx-1)" }}>{l}</div>)}
            {frame.status !== "done" && frame.status !== "error" && <span style={{ color: "var(--accent-2)" }}>▌</span>}
          </div>
        </div>
      </div>
    </>
  );
}

/* ============================ CONTROLLER ================================= */
function IngestScreen() {
  const ctx = React.useContext(VDCtx);
  const [flow, setFlow] = React.useState(ctx.route.flow || "hub");
  const [connecting, setConnecting] = React.useState(false);
  const pick = (id) => { if (id === "connect") setConnecting(true); else setFlow(id); };
  return (
    <>
      {flow === "hub" && <SourceHub onPick={pick} />}
      {flow === "local" && <LocalIngestFlow onExit={() => setFlow("hub")} />}
      {flow === "video" && <VideoIngestFlow onExit={() => setFlow("hub")} />}
      {(flow === "import" || flow === "media") && <window.ImportFlow mode={flow} onExit={() => setFlow("hub")} ProcessingView={ProcessingView} DoneView={DoneView} DropZone={DropZone} />}
      {connecting && <ConnectModal onClose={() => setConnecting(false)} />}
    </>
  );
}

function ConnectModal({ onClose }) {
  const [host, setHost] = React.useState("/data3/ssharma8/datasets/incoming/");
  const [done, setDone] = React.useState(false);
  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, background: "rgba(4,6,10,.66)", backdropFilter: "blur(3px)", zIndex: 90, display: "grid", placeItems: "center" }} className="fade">
      <div onClick={(e) => e.stopPropagation()} className="card pop" style={{ width: 440, maxWidth: "92vw", boxShadow: "var(--shadow-pop)" }}>
        <div style={{ padding: "16px 20px", borderBottom: "1px solid var(--line)", display: "flex", alignItems: "center", gap: 10 }}><Icon name="link" size={18} style={{ color: "var(--m-fd)" }} /><div style={{ fontWeight: 700, fontSize: 15 }}>Watch a folder</div><div style={{ flex: 1 }} /><button className="btn ghost icon" onClick={onClose}><Icon name="x" size={16} /></button></div>
        {done ? (
          <div style={{ padding: 28, textAlign: "center" }}>
            <div style={{ width: 46, height: 46, margin: "0 auto 12px", borderRadius: "50%", background: "var(--match-soft)", border: "2px solid var(--match)", display: "grid", placeItems: "center", color: "var(--match)" }}><Icon name="check" size={24} /></div>
            <div style={{ fontWeight: 700, fontSize: 15 }}>Watching {host}</div>
            <div style={{ fontSize: 12.5, color: "var(--tx-2)", marginTop: 4 }}>New media will auto-ingest hourly with the default pipeline.</div>
            <button className="btn primary" style={{ marginTop: 16 }} onClick={onClose}>Done</button>
          </div>
        ) : (
          <>
            <div style={{ padding: 20, display: "flex", flexDirection: "column", gap: 14 }}>
              <div><div style={{ fontSize: 11, fontWeight: 600, color: "var(--tx-2)", textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8 }}>Folder path</div><input value={host} onChange={(e) => setHost(e.target.value)} className="mono" style={{ width: "100%", background: "var(--bg-2)", border: "1px solid var(--line-2)", borderRadius: 7, color: "var(--tx-0)", fontSize: 12.5, padding: "9px 11px", outline: "none" }} /></div>
              <div style={{ display: "flex", gap: 10 }}>
                <div style={{ flex: 1 }}><div style={{ fontSize: 11, color: "var(--tx-2)", marginBottom: 6 }}>Schedule</div><select style={{ width: "100%", background: "var(--bg-3)", border: "1px solid var(--line-2)", borderRadius: 7, color: "var(--tx-0)", padding: "8px", fontSize: 12 }}><option>Every hour</option><option>Every 15 min</option><option>On new object</option></select></div>
                <div style={{ flex: 1 }}><div style={{ fontSize: 11, color: "var(--tx-2)", marginBottom: 6 }}>Pipeline</div><select style={{ width: "100%", background: "var(--bg-3)", border: "1px solid var(--line-2)", borderRadius: 7, color: "var(--tx-0)", padding: "8px", fontSize: 12 }}><option>Auto-label (AMOD)</option><option>Import labels</option><option>Stage only</option></select></div>
              </div>
            </div>
            <div style={{ padding: "13px 20px", borderTop: "1px solid var(--line)", display: "flex", gap: 10, justifyContent: "flex-end" }}><button className="btn ghost" onClick={onClose}>Cancel</button><button className="btn primary" onClick={() => setDone(true)}><Icon name="link" size={15} />Watch source</button></div>
          </>
        )}
      </div>
    </div>
  );
}

Object.assign(window, { IngestScreen, ProcessingView, DoneView, DropZone, ingestHelpers: { fmtDur, estFrames, SAMPLE_MODES, posterFor } });
